### ISSUE TITLE
Not work in Telegram

### ISSUE THREAD

**Issue by ATAfella** [Ghir0/amazon-referral-random-bot#2]
Hi,
I follow all the step for configurate a new bot but on telegram there is a problem:

Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"YOU_BLOCKED_USER"}

I don't why.
Can you help me?

**Comment by Ghir0** [comment]
No issues here.
I have 2 bot set up and no errors coming.
Hope you just misconfigured something.

I use heroku to deploy the code.
